version: '2'

services:

  mariadb:
    image: mariadb
    container_name: "${project_prefix}-mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD: 'test'
      - MYSQL_USER: 'admin'
      - MYSQL_PASSWORD: 'test'
    ports:
      - "3306:3306"
    volumes:
      - "./sqldata:/var/lib/mysql"

  php7:
    container_name: "${project_prefix}-php7"
    env_file:
      - "./.env"
    ports:
      - "9000:9000"
    links:
      - "mariadb"
    volumes:
      - "${project_source}:/home/sites/project"
  nginx:
    build:
      context: "./nginx"
    container_name: "${project_prefix}-nginx"
    env_file:
      - "./.env"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php7"
    volumes:
      - "${project_source}:/home/sites/project"